# Publish build artifacts
# Publish build artifacts to Azure Pipelines or a Windows file share
pr:
  - main

steps:
- task: CopyFiles@1
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop 2' 
    publishLocation: 'Container' # Options: container, filePath
    storeAsTar: true # Optional
